apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: mern-cluster
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30000
      hostPort: 27017
      protocol: TCP
    - containerPort: 30001
      hostPort: 3000
      protocol: TCP
    - containerPort: 30002
      hostPort: 4000
      protocol: TCP